### ISSUE TITLE
Tensorflow GPU libarary Libcudart.so.11.0 not found

### ISSUE THREAD

**Issue by Dipankar1997161** [david8862/tf-keras-stacked-hourglass-keypoint-detection#13]
I am using TensorFlow both CPU and GPU version 2.8 but everytime I try to import the libcuda file is not found, 
I tried different versions are cuda but nothing seems to work.

Once, cudatoolkit 11.1 with cudnn 8.1 worked but now that's not working either. 

I am now confused about which version would be suitable and If I go TensorFlow 2.4 then the TensorFlow model optimization library doesn't match with the other versions..

Could you help me in anyway out here @david8862

**Comment by Dipankar1997161** [comment]
thank you! I solved it by exporting the path manually for the libcuda files. 

Therefore, I close the issue here.
